language: ruby
rvm:
  - 2.3.3

install: gem install jekyll -v 3.3.1

script:
  - jekyll build

branches:
  only:
    - master

  #before_script:
    #- npm install -g firebase-tools


  #after_success:
    #- firebase deploy --token=${FIREBASE_API_TOKEN}
