language: node_js
node_js:
  - "5.11"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - master

  before_script:
    - npm install -g firebase-tools

  script:
    - firebase serve

  after_success:
    - firebase deploy --token=${FIREBASE_API_TOKEN}
