language: node_js
node_js:
  - 7.5.0

install: 
  - rvm install 2.2.3
  - gem install jekyll -v 3.3.1
  - npm install -g firebase-tools

script:
  - jekyll build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}

branches:
  only:
    - master

  #before_script:
    #- npm install -g firebase-tools


