language: ruby
rvm:
  - 2.3.3

branches:
  only:
    - master

  #before_script:
    #- npm install -g firebase-tools

  script:
    - jekyll build

  #after_success:
    #- firebase deploy --token=${FIREBASE_API_TOKEN}
