language: ruby
rvm:
  - 2.3.3

install: 
  - gem install jekyll -v 3.3.1
  - gem install dpl

script:
  - jekyll build

after_success:
  - dpl --provider=firebase --token=${FIREBASE_API_TOKEN} --project=testcdn-1dd95 --skip_cleanup

branches:
  only:
    - master
